# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e364d96a1fdf6ab4000055e65e25e4bd304c6fea3eb9ad1e3e747122bf3773f600da9d769fa343dea3eab0d89adfb1d565ec3561ccdad8d569e6b0eeefaf1de

test:
  secret_key_base: 56ea2dfc69517f42c64af7547499a4cf84906881a826c7e702fe9e49ae26d155b19475d514c482438c9c69709870f518e167e7057556d91445e6fc5604517bea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
